# Generated by Django 2.0.2 on 2018-03-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
