# Generated by Django 2.0.2 on 2018-03-04 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20180302_0150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Code',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='code',
        ),
    ]
