# Generated by Django 2.0.2 on 2018-03-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20180312_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name='date out'),
        ),
    ]
